### ISSUE TITLE
Timeline Tracing Roadmap

### ISSUE THREAD

**Issue by zhongzc** [pingcap-incubator/tidb-dashboard#710]
# Related Feature Request

#552, pingcap/tidb#17693

# Related Project

[project#23](https://github.com/pingcap-incubator/tidb-dashboard/projects/23)

# Library Development

Many existing tracing libraries are powerful, easy-to-use, and convenient to integrate with other existing components. Unfortunately, almost none of them perform well in terms of performance. For that, lightweight, efficient, and performant tracing libraries for both TiKV and TiDB need to be developed to meet performance requirements. Hopefully, runtime information will be collected constantly so that details of uncommon problems can be caught.

- [ ] [minitrace-rust](https://github.com/pingcap-incubator/minitrace-rust) for TiKV
  - [x] implement prototype
  - [x] micro and integration benchmark
  - [x] [desgin docs](https://docs.google.com/document/d/1pA-9-kgfhnt600qx2pKim0-0V7pat0hyNIjz1O4EvI4) (in Chinese)
  - [x] measure time with high performance: [lib/minstant](https://github.com/zhongzc/minstant)
  - [x] support properies: pingcap-incubator/minitrace-rust#17
  - [ ] **one-dimensionaize spans to simplify usage (WIP):** pingcap-incubator/minitrace-rust#19
- [ ] [minitrace-go](https://github.com/pingcap-incubator/minitrace-go) for TiDB
  - [x] implement prototype
  - [ ] micro and integration benchmark
    - [ ] investigate cost of time measure with different clock sources
  - [ ] design docs

# Apply to Codebase

After finishing library development, applying the library to the codebase is the next work to do.

- [ ] Apply to TiKV
    - [ ] **collect tracing demands from TiKV (WIP):** [docs](https://docs.google.com/document/d/11WCXmfCAkVxEUjhD0LDGMTU2TJY2zZHXObEbSYFZopY/) (in Chinese)
    - [ ] put tracing points to procedures wanted to trace
      - [ ] handle old async codes of producer/consumer model
- [ ] Apply to TiDB

# Full Integration

Without intervention, all tracing results only reside in memory. However, tracing results of requests associated with a SQL statement or a transaction always need some ways to collect when we intend to show them. These following questions may be of interest to us: 

  1. How, when, and where to store them?
  2. How to fetch them?

Due to the size of tracing results is not small commonly, I/O is always a difficult problem we have to face. It will have a cost that cannot be ignored whether results are persisted to disks or transmitted through the network. Therefore, most Careful design and most meticulous tests are needed here.

- [ ] Handle tracing results from TiKV
  - [x] [trade-off docs](https://docs.google.com/document/d/1zvp_myxUnd38xSTWmNbtW-2ltQ1ZtP_4QxWIzgiitQw) (in Chinese)
  - [ ] gather and send back to TiDB
    - [ ] filtering if amount of spans is too big
      - [ ] **one-dimensionaize spans and sort them by begin time (WIP)**
    - [ ] **reply or not according to threshold of execution time (WIP)**
    - [ ] **serialize results to flatbuffers (WIP)**
    - [ ] embed the serialized result into grpc responses
- [ ] Handle all tracing results at TiDB

# UI

In order to maximize the usability of tracing, a user-friendly UI is essential. People can visually see what's happening during the execution of a SQL statement / a transaction intuitively.

- [ ] UX/UI design
- [ ] Frontend implementation
- [ ] Data fetching and integration
